### PR TITLE
Added aarch64 support

### PR DESCRIPTION
**Pull request by ThinkerPal**
pls review ty 🙏

### CODE REVIEW

**Review by jiachenyee — APPROVED** [review]
lgtm

**Comment by ThinkerPal** [comment]
thanks u

**Comment by ThinkerPal** [comment]
pls merge ty :prayge:

**Comment by ThinkerPal** [comment]
tyty

**Comment by ThinkerPal** [comment]
i delete now

**Comment by qin-guan** [comment]
lgtm

**Pull request merged**
